#!/usr/bin/env bash

workdir=$(dirname $(readlink -f $BASH_SOURCE))/../

pushd $workdir

for i in `find ./data/tap -name *.json`; do
    homepage=$(jq -r .homepage $i)
    if [[ $homepage =~ 'github.com' ]]; then
        [ -n "$GITHUB_TOKEN" ] && AUTH_HEADER="Authorization: token $GITHUB_TOKEN"

        if ! (jq -e '.readme' $i ) ; then
            
            readme=$(echo -n $homepage | sed -E 's#github.com/(.+)#api.github.com/repos/\1/readme#g')
            echo $readme
            content=$((curl -H "$AUTH_HEADER" -sq $readme | jq -r .content | base64 -d) || echo -n '')

            if [[ -n "$content" ]]; then
                jq --arg readme $content '. + { readme: $readme }' $i > $i.enhanced
            else
                echo 'Requested readme content is empty, this could be due to rate-limiting. TBD.'
            fi

        fi
    fi

done

trap popd EXIT