#!/usr/bin/env bash

workdir=$(dirname $(readlink -f $BASH_SOURCE))/../

if [[ -z "$GITHUB_TOKEN" ]]; then
    echo "The github token is not set, this is necessary because we will be hitting the github api, set it and then run this script again."
    echo 'You can probably do this by running the following command in the terminal: `export GITHUB_TOKEN=$(github auth token)'
    exit -1
fi



pushd $workdir

for i in `find ./data/tap -name *.json | sort`; do
    homepage=$(jq -r .homepage $i)
    if [[ $homepage =~ 'github.com' ]]; then
        (
        if ! (jq -e '.readme' $i > /dev/null ) ; then
            echo -e "\nGetting readme for $i"
            readme=$(echo -n $homepage | sed -E 's#github.com/(.+)#api.github.com/repos/\1readme#g')
            
            content=$((curl -H "Authorization: token $GITHUB_TOKEN" -fsq $readme | jq -r .content | base64 -d) || echo -n '')
            if [[ -n "$content" ]]; then
                jq --arg readme "$content" '. + { readme: $readme }' $i > $i.enhanced
                mv $i.enhanced $i
            else
                jq 'del(.readme)' $i > $i.cleaned
                mv $i.cleaned $i
                echo -e "\nRequested readme content is empty for $readme"
            fi
            
        else
            echo -n '.' # show some progress.
        fi
        ) &
    fi

done

wait

trap popd EXIT