#!/usr/bin/env bash
workdir=$(dirname $(readlink -f $BASH_SOURCE))/../

date > .freshen
git add .freshen
git commit -am 'Freshen the repo so that github workflows continue to execute.'
git push

trap popd EXIT