#!/usr/bin/env bash
set -exuo pipefail

srcdir=$(dirname $(readlink -f $BASH_SOURCE))
workdir=$srcdir/../

pushd $workdir
brew update

taps=('homebrew/core')

for tap in "${taps[@]}"; do
    echo making $tap dir.
    target=$workdir/data/$tap
    # make the target directory if it does not exist, but ignore if it already exists (|| true)
    mkdir -p $target || true

    tap_path=$(brew --repo $tap)
    formula_path=./Formula

    pushd $tap_path

    original=$(git rev-list --max-parents=0 HEAD)
    for i in $(comm -23 <(ls $formula_path | sed -E 's#[.]rb$##g' | sort) <(ls $target | sed -E 's#[.]json$##g' | sort)); do
        pkg=$i
        echo "Constructing entry for '$pkg'..."
        pwd
        git bisect start HEAD $original
        git bisect run test -f $formula_path/$pkg.rb

        create_date=$(git log --oneline --format='.date_added="%cI"' --date=iso -- $pkg.rb | head -n1)
        echo $create_date
        git bisect reset
        brew info $pkg --json | jq ".[] | $create_date" >$target/$pkg.json
    done
    popd
done

popd
