#!/usr/bin/env bash
set -ue

workdir=$(dirname $(readlink -f $BASH_SOURCE))/../generator
pushd $workdir

exec 3>&1


nohup dotnet run -- preview >&3 2>&3 &
proc1=$!

function close(){
    kill -9 $proc1
    popd
}

trap close EXIT

tailwindcss -w -m -o ./input/public/main.css