#!/usr/bin/env bash

workdir=$(dirname $(readlink -f $BASH_SOURCE))/../
pushd $workdir

docker run --rm -v $PWD:/data -w /data -it homebrew/brew:4.1.4 \
    bash -c '/data/scripts/get-formula-data build_graph'

trap popd EXIT
